# Generated by Django 6.1 on 2026-08-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('contato', models.CharField(blank=True, max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('grupo_muscular', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('braco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('torax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('perna', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('suprailiaca', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('panturrilha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('triceps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(blank=True, null=True)),
                ('repeticoes', models.PositiveIntegerField(blank=True, null=True)),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('adaptacao', models.TextField(blank=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_treino', to='core.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.treino')),
            ],
        ),
    ]
